<?php

namespace jeus\JoueurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends EntityRepository
{
    
    public function findJoueurEnAttente($Joueur) {
        return $this->createQueryBuilder('j')
                ->where('j.enAttenteQuickstrike=true')
                ->andWhere('j<>:Joueur')
                ->setParameter('Joueur', $Joueur)
                ->getQuery()
                ->getResult();        
    }
    
    
}
