security:
    encoders:
        jeus\JoueurBundle\Entity\Joueur: sha512 

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        main:
            entity: { class: jeus\JoueurBundle\Entity\Joueur, property: username }
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:   ^/login$
            anonymous: true

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
                invalidate_session: false


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN  }
