<?php

namespace jeus\QuickstrikeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TraitCarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraitCarteRepository extends EntityRepository
{
}
