## Quickstrike ##
jeus_quickstrike:
    path:     /
    defaults: { _controller: jeusQuickstrikeBundle:Quickstrike:index }
    
jeus_quickstrike_carte:
    path:     /carte
    defaults: { _controller: jeusQuickstrikeBundle:Carte:carte }
    
jeus_quickstrike_deck:
    path:     /deck
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckListe }
    
jeus_quickstrike_deck_creer:
    path:     /deck/creer/
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckCreer }
    
jeus_quickstrike_deck_editer:
    path:     /deck/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckEditer }
    requirements:
        id: \d+
    
jeus_quickstrike_deck_supprimer:
    path:     /deck/supprimer/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckSupprimer }
    requirements:
        id: \d+
    options:
        expose: true
    
jeus_quickstrike_deck_renommer:
    path:     /deck/renommer/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckRenommer }
    requirements:
        id: \d+
    options:
        expose: true
    
jeus_quickstrike_deck_ajouterCarte:
    path:     /deck/ajouter-carte/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckAjouterCarte }
    requirements:
        id: \d+
    options:
        expose: true
    
jeus_quickstrike_deck_supprimerCarte:
    path:     /deck/supprimer-carte/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Deck:deckSupprimerCarte }
    requirements:
        id: \d+
    options:
        expose: true
    
jeus_quickstrike_joueur_enAttente:
    path:     /joueur/en-attente
    defaults: { _controller: jeusQuickstrikeBundle:Partie:joueurEnAttente }
    options:
        expose: true
    
jeus_quickstrike_joueur_annulerAttente:
    path:     /joueur/annuler-attente
    defaults: { _controller: jeusQuickstrikeBundle:Partie:joueurAnnulerAttente }
    options:
        expose: true
    
jeus_quickstrike_joueur_affronter:
    path:     /joueur/affronter/{idJoueur}
    defaults: { _controller: jeusQuickstrikeBundle:Partie:joueurAffronter }
    requirements:
        idJoueur: \d+
    options:
        expose: true
    
jeus_quickstrike_parties:
    path:     /parties
    defaults: { _controller: jeusQuickstrikeBundle:Partie:index }
    
jeus_quickstrike_partie_entrainement:
    path:     /partie-entrainement
    defaults: { _controller: jeusQuickstrikeBundle:Partie:entrainement }
    
jeus_quickstrike_partie:
    path:     /partie/{id}
    defaults: { _controller: jeusQuickstrikeBundle:Partie:partie }
    requirements:
        id: \d+
    
jeus_quickstrike_partie_inverser:
    path:     /partie/{id}/inverser
    defaults: { _controller: jeusQuickstrikeBundle:Partie:inverser }
    requirements:
        id: \d+
    
jeus_quickstrike_partie_choix_deck:
    path:     /partie/{id}/choix-deck/{idDeck}
    defaults: { _controller: jeusQuickstrikeBundle:Partie:choixDeck }
    requirements:
        id: \d+
        idDeck: \d+
    
