services:
#    itroom_metier.example:
#        class: Itroom\MetierBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    jeus_quickstrike_tools:
        class: jeus\QuickstrikeBundle\Services\Tools

    jeus_quickstrike_effets:
        class: jeus\QuickstrikeBundle\Services\Effets
        arguments: [@jeus_quickstrike_tools,@jeus_quickstrike_interactions]

    jeus_quickstrike_interactions:
        class: jeus\QuickstrikeBundle\Services\Interactions
        arguments: [@doctrine.orm.entity_manager,@jeus_quickstrike_tools]

    jeus_quickstrike_carte:
        class: jeus\QuickstrikeBundle\Services\Carte
        arguments: [@doctrine.orm.entity_manager,@service_container]
        scope: request

    jeus_quickstrike_partie:
        class: jeus\QuickstrikeBundle\Services\Partie
        arguments: [@doctrine.orm.entity_manager,@service_container,@jeus_quickstrike_tools,@jeus_quickstrike_effets,@jeus_quickstrike_interactions,@router]
        scope: request

    jeus_quickstrike_saveBdd:
        class: jeus\QuickstrikeBundle\Services\SaveBdd
        arguments: [@service_container]

